ATTR_MAIN_TEST = 'main_test'
ATTR_PLATFORM = 'platform'
ATTR_ARGS = 'args'
ATTR_SENSOR_DATA_CONNECTOR = 'sensor_data_connector'
ATTR_SENSOR_DATA_PARSER = 'sensor_data_parser'
ATTR_DATABASE = 'database'

ATTR_LEARNING_MODE = 'learning_mode'
ATTR_CURRENT_LOOP = 'current_loop'

RESULT_PASS = 'pass'
RESULT_FAIL = 'fail'
RESULT_UNKNOWN = 'unknown'
REASON = 'reason'
ATTR_RESULT = 'result'

ATTR_VALUES = 'v'
ATTR_TIMESTAMP = 't'
ATTR_SENSOR_NAME = 'n'

KEY_ATOM_LOOP = 'loop'
KEY_ATOM_INDEX = 'idx'
KEY_VALUE = 'v'
KEY_ATOM_NAME = 'atom_name'
KEY_ATOM_DURATION = 'atom_dur'
KEY_ATOM_STATUS = 'stat'
KEY_TEST_NAME = 'test_name'
KEY_TEST_LOOPS = 'loops'
# KEY_START_TIME = 'start_time'
# KEY_STOP_TIME='stop_time'
KEY_REFERENCE_DATA = 'reference_data'
KEY_ERROR = 'error'

ATOM_STATUS_EXECUTED = 'COMMAND EXECUTED'
ATOM_STATUS_EXECUTING = 'Executing command'
ATOM_STATUS_COLLECTING = 'Collecting sensor data'

# WEB_SOCKET DATA #######################################
KEY_SUBJECT = 'subj'
KEY_CACHE = 'cache'
KEY_TYPE = 'type'
KEY_DATA = 'data'
